
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-f25/proj-happycows-f25-15
owner: ucsb-cs156-f25
repo_name: proj-happycows-f25-15
pull_requests: [{"author":{"id":"U_kgDOB1PefA","is_bot":false,"login":"guntashgill","name":""},"headRefName":"ggWireMock","number":10,"title":"Gg wire mock","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-15/pull/10"},{"author":{"id":"MDQ6VXNlcjc1NTA5OTg0","is_bot":false,"login":"AkulS1008","name":"Akul Singh"},"headRefName":"feature/akul/dev-page","number":9,"title":"Adding a DeveloperInfo Page to all Admin Dropdown Pages","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-15/pull/9"},{"author":{"id":"U_kgDOB1PefA","is_bot":false,"login":"guntashgill","name":""},"headRefName":"ggRestoreTitle","number":8,"title":"gg changed frontend name to HappyCows along with logo and included teâ€¦","url":"https://github.com/ucsb-cs156-f25/proj-happycows-f25-15/pull/8"}]
